@startuml UC02_Creation_Festival

left to right direction
skinparam packageStyle rectangle

actor "Admin" as org

rectangle "Création d'un Festival" {
  usecase "Créer nouveau festival" as UC2
  usecase "Saisir nom du festival" as UC2_1
  usecase "Définir nombre de zones tarifaires" as UC2_2
  usecase "Définir zone tarifaire" as UC2_3
  usecase "Saisir nom de la zone" as UC2_3_1
  usecase "Saisir nombre de tables" as UC2_3_2
  usecase "Saisir prix table" as UC2_3_3
  usecase "Saisir prix m2" as UC2_3_4
}

org --> UC2

UC2 ..> UC2_1 : <<include>>
UC2 ..> UC2_2 : <<include>>
UC2 ..> UC2_3 : <<include>>
UC2_3 ..> UC2_3_1 : <<include>>
UC2_3 ..> UC2_3_2 : <<include>>
UC2_3 ..> UC2_3_3 : <<include>>
UC2_3 ..> UC2_3_4 : <<include>>

note right of UC2_1
  Le nom doit être unique
end note


@enduml
