@startuml UC04_Edition_Editeur

left to right direction
skinparam packageStyle rectangle

actor "Adm" as adm

rectangle "Édition/Création Éditeur" {
  usecase "Éditer/Créer éditeur" as UC4
  usecase "Saisir nom éditeur" as UC4_1
  usecase "Gérer contacts" as UC4_2
  usecase "Ajouter contact" as UC4_2_1
  usecase "Supprimer contact" as UC4_2_2
  usecase "Gérer liste jeux" as UC4_3
  usecase "Ajouter jeu" as UC4_3_1
  usecase "Supprimer jeu" as UC4_3_2
}

adm --> UC4

UC4 ..> UC4_1 : <<include>>
UC4 ..> UC4_2 : <<include>>
UC4 ..> UC4_3 : <<include>>
UC4_2 ..> UC4_2_1 : <<extend>>
UC4_2 ..> UC4_2_2 : <<extend>>
UC4_3 ..> UC4_3_1 : <<extend>>
UC4_3 ..> UC4_3_2 : <<extend>>

@enduml