@startuml UC09_Info_Reservation

left to right direction
skinparam packageStyle rectangle

actor "Admin" as adm

rectangle "Informations sur la Réservation" {
  usecase "Gérer info réservation" as UC9
  usecase "Indiquer qui présente jeux" as UC9_1
  usecase "Éditeur présente" as UC9_1_1
  usecase "Bénévoles présentent" as UC9_1_2
  usecase "Gérer liste jeux " as UC9_2
  usecase "Demander liste jeux" as UC9_2_1
  usecase "Obtenir liste jeux" as UC9_2_2
  usecase "Marquer jeux reçus" as UC9_2_3
}

adm --> UC9

UC9 ..> UC9_1 : <<include>>
UC9_1 <|-- UC9_1_1
UC9_1 <|-- UC9_1_2
UC9 ..> UC9_2 : <<extend>>
UC9_2 ..> UC9_2_1 : <<extend>>
UC9_2 ..> UC9_2_2 : <<extend>>
UC9_2 ..> UC9_2_3 : <<extend>>


@enduml