@startuml UC13_Liste_Jeux_Festival

left to right direction
skinparam packageStyle rectangle

actor "Admin" as adm

rectangle "Liste des Jeux du Festival" {
  usecase "Afficher jeux du festival" as UC13
  usecase "Afficher détails jeu" as UC13_1
  usecase "Afficher zone plan" as UC13_2
  usecase "Trier par nom" as UC13_3
  usecase "Trier par auteur" as UC13_4
  usecase "Trier par éditeur" as UC13_5
  usecase "Trier par zone plan" as UC13_6
}

adm --> UC13

UC13 ..> UC13_1 : <<include>>
UC13 ..> UC13_2 : <<include>>
UC13 ..> UC13_3 : <<extend>>
UC13 ..> UC13_4 : <<extend>>
UC13 ..> UC13_5 : <<extend>>
UC13 ..> UC13_6 : <<extend>>

@enduml